#!/usr/bin/env bash

set -e

SOURCE_DIR="${BASH_SOURCE[0]%/*}"
TEMPLATE_FILE="${SOURCE_DIR}/template.bash"

NAMESPACE="${1:?Missing namespace argument.}"
EXECUTABLE="${2:?Missing executable argument.}"
TARGET_FILE="${3:?Missing target file argument.}"

if ! [[ -f "${TEMPLATE_FILE}" ]]; then
  echo "could not find template file at '${TEMPLATE_FILE}'"
  exit 1
fi

TEMPLATE_CONTENT="$(< "${TEMPLATE_FILE}")"
TEMPLATE_CONTENT="$(echo "${TEMPLATE_CONTENT}" | sed -ne '/^# completion function$/,$p')"

if ! [[ -f "${TARGET_FILE}" ]]; then
  echo "could not find source file at '${TARGET_FILE}'"
  exit 1
fi

TARGET_CONTENT="$(< "${TARGET_FILE}")"
TARGET_CONTENT="$(echo "${TARGET_CONTENT}" | sed -ne '1,/^# completion function$/p' | sed -e '$d')"

TEMPLATE_CONTENT="$(echo "${TEMPLATE_CONTENT}" | sed -e "s/^# NAMESPACE={{bc_namespace}}\$/# NAMESPACE=${NAMESPACE}/")"
TEMPLATE_CONTENT="$(echo "${TEMPLATE_CONTENT}" | sed -e "s/^# EXECUTABLE={{bc_executable}}\$/# EXECUTABLE=${EXECUTABLE}/")"
TEMPLATE_CONTENT="$(echo "${TEMPLATE_CONTENT}" | sed -e "s/command_current={{bc_executable}} /command_current=${EXECUTABLE} /")"
TEMPLATE_CONTENT="$(echo "${TEMPLATE_CONTENT}" | sed -e "s/_{{bc_namespace}}_/_${NAMESPACE}_/")"
TEMPLATE_CONTENT="$(echo "${TEMPLATE_CONTENT}" | sed -e "s/_${NAMESPACE}_{{bc_executable}}/_${NAMESPACE}_${EXECUTABLE}/")"

echo -e "${TARGET_CONTENT}\n\n${TEMPLATE_CONTENT}" > "${TARGET_FILE}"
